# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条码号')),
                ('status', models.CharField(choices=[('available', '可借阅'), ('borrowed', '已借出'), ('reserved', '已预约'), ('lost', '丢失'), ('damaged', '损坏'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='馆藏位置')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('total_copies', models.IntegerField(default=1, verbose_name='总册数')),
                ('available_copies', models.IntegerField(default=1, verbose_name='可借册数')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='封面图片')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'book_categories',
            },
        ),
        migrations.CreateModel(
            name='BorrowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('max_borrow_days', models.IntegerField(default=30, verbose_name='最长借阅天数')),
                ('max_renew_count', models.IntegerField(default=2, verbose_name='最大续借次数')),
                ('max_borrow_books', models.IntegerField(default=10, verbose_name='最大借阅数量')),
                ('overdue_fine_per_day', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='每日逾期罚款')),
            ],
            options={
                'verbose_name': '借阅配置',
                'verbose_name_plural': '借阅配置',
                'db_table': 'borrow_configs',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期'), ('lost', '已丢失'), ('renewed', '已续借')], default='borrowed', max_length=20, verbose_name='状态')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借阅日期')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('renew_count', models.IntegerField(default=0, verbose_name='续借次数')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('overdue_fine', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期罚款')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='borrowing.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrow_records',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
