export enum Role {
  ADMIN = 'ADMIN',
  SERVICE_MANAGER = 'SERVICE_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  TECHNICIAN = 'TECHNICIAN',
}

export enum Permission {
  REPAIR_ORDER_VIEW = 'REPAIR_ORDER_VIEW',
  REPAIR_ORDER_CREATE = 'REPAIR_ORDER_CREATE',
  REPAIR_ORDER_EDIT = 'REPAIR_ORDER_EDIT',
  REPAIR_ORDER_DELETE = 'REPAIR_ORDER_DELETE',
  PART_APPLICATION_VIEW = 'PART_APPLICATION_VIEW',
  PART_APPLICATION_CREATE = 'PART_APPLICATION_CREATE',
  PART_APPLICATION_EDIT = 'PART_APPLICATION_EDIT',
  PART_APPLICATION_APPROVE = 'PART_APPLICATION_APPROVE',
  PART_APPLICATION_REJECT = 'PART_APPLICATION_REJECT',
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_EDIT = 'INVENTORY_EDIT',
  INVENTORY_LOCK = 'INVENTORY_LOCK',
  INVENTORY_UNLOCK = 'INVENTORY_UNLOCK',
  USER_MANAGE = 'USER_MANAGE',
  EXPORT_DATA = 'EXPORT_DATA',
  VIEW_LOGS = 'VIEW_LOGS',
}

export enum RepairOrderStatus {
  PENDING_QUOTATION = 'PENDING_QUOTATION',
  QUOTATION_SENT = 'QUOTATION_SENT',
  QUOTATION_APPROVED = 'QUOTATION_APPROVED',
  QUOTATION_REJECTED = 'QUOTATION_REJECTED',
  AWAITING_PARTS = 'AWAITING_PARTS',
  IN_REPAIR = 'IN_REPAIR',
  REPAIR_COMPLETED = 'REPAIR_COMPLETED',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  PICKED_UP = 'PICKED_UP',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum PartApplicationStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  PARTIAL_APPROVED = 'PARTIAL_APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum InventoryLockStatus {
  ACTIVE = 'ACTIVE',
  CONSUMED = 'CONSUMED',
  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED',
}

export enum NoteType {
  INTERNAL = 'INTERNAL',
  CUSTOMER_REPLY = 'CUSTOMER_REPLY',
  REJECT_REASON = 'REJECT_REASON',
  SUPPLEMENT = 'SUPPLEMENT',
  FOLLOWUP = 'FOLLOWUP',
  SYSTEM = 'SYSTEM',
}

export type PermissionType = Permission;
export type RoleType = Role;
