// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/1/2026, 12:41:35 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/components/common/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/components/dashboard/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/components/layout/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/components/workorder/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/plugins/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/composables/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/utils/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-4/watch-service-system/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;