# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('category', models.CharField(choices=[('air_conditioner', '空调'), ('lighting', '照明'), ('computer', '电脑'), ('printer', '打印机'), ('scanner', '扫描仪'), ('security', '安防设备'), ('furniture', '家具'), ('other', '其他')], default='other', max_length=30, verbose_name='设备分类')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('warranty_expire', models.DateField(blank=True, null=True, verbose_name='保修截止')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '异常'), ('faulty', '故障'), ('repairing', '维修中'), ('scrapped', '已报废')], default='normal', max_length=20, verbose_name='设备状态')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('description', models.TextField(blank=True, verbose_name='设备描述')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'ordering': ['code'],
            },
        ),
    ]
