// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2026, 7:36:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/plugins/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/composables/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/utils/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-3/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;