# Generated by Django 4.2.30 on 2026-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='用户代理'),
        ),
    ]
