# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('environment', '环境卫生'), ('facility', '设施设备'), ('security', '安全消防'), ('service', '服务规范'), ('other', '其他')], default='other', max_length=30, verbose_name='检查项分类')),
                ('name', models.CharField(max_length=200, verbose_name='检查项名称')),
                ('description', models.TextField(blank=True, verbose_name='检查标准')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '检查项',
                'verbose_name_plural': '检查项',
                'db_table': 'check_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '巡检图片',
                'verbose_name_plural': '巡检图片',
                'db_table': 'inspection_images',
            },
        ),
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_name', models.CharField(max_length=200, verbose_name='检查项名称')),
                ('item_category', models.CharField(choices=[('environment', '环境卫生'), ('facility', '设施设备'), ('security', '安全消防'), ('service', '服务规范'), ('other', '其他')], max_length=30, verbose_name='检查项分类')),
                ('is_passed', models.BooleanField(null=True, verbose_name='是否通过')),
                ('result_value', models.TextField(blank=True, verbose_name='检查结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('has_issue', models.BooleanField(default=False, verbose_name='发现问题')),
                ('issue_description', models.TextField(blank=True, verbose_name='问题描述')),
                ('need_repair', models.BooleanField(default=False, verbose_name='需要报修')),
            ],
            options={
                'verbose_name': '巡检项结果',
                'verbose_name_plural': '巡检项结果',
                'db_table': 'inspection_item_results',
            },
        ),
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('type', models.CharField(choices=[('daily', '日常巡检'), ('weekly', '周巡检'), ('monthly', '月巡检'), ('special', '专项巡检')], default='daily', max_length=20, verbose_name='巡检类型')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '巡检计划',
                'verbose_name_plural': '巡检计划',
                'db_table': 'inspection_plans',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('daily', '日常巡检'), ('weekly', '周巡检'), ('monthly', '月巡检'), ('special', '专项巡检')], default='daily', max_length=20, verbose_name='巡检类型')),
                ('title', models.CharField(max_length=200, verbose_name='巡检标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('needs_review', '需回查'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('overall_rating', models.IntegerField(blank=True, null=True, verbose_name='总体评分')),
                ('remarks', models.TextField(blank=True, verbose_name='巡检备注')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comments', models.TextField(blank=True, verbose_name='审核意见')),
                ('needs_review_reason', models.TextField(blank=True, verbose_name='需回查原因')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
