// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/parts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/parts.get').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/workorders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workorders.get').default>>>>
    }
    '/api/workorders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workorders/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workorders/[id].patch').default>>>>
    }
    '/api/workorders/:id/action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workorders/[id]/action.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}