# Generated by Django 4.2.30 on 2026-05-29 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('URGENT', '紧急')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collection_reminder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_days', models.IntegerField(default=30)),
                ('credit_status', models.CharField(choices=[('NORMAL', '正常'), ('WARNING', '预警'), ('OVERDUE', '逾期'), ('FROZEN', '冻结')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('INQUIRY', '询价中'), ('INQUIRY_APPROVED', '询价已确认'), ('LOCKED', '已锁库'), ('DELIVERED', '已出库'), ('SETTLED', '已结算'), ('RETURN_REQUESTED', '退货申请中'), ('RETURN_APPROVED', '退货已批准'), ('RETURN_REJECTED', '退货已驳回'), ('RETURNED', '已退货'), ('PAID_PARTIAL', '部分回款'), ('PAID', '已结清'), ('OVERDUE', '已逾期'), ('CANCELLED', '已取消')], default='INQUIRY', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_days', models.IntegerField(default=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.customer')),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('warehouse_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('ENGINE', '发动机件'), ('CHASSIS', '底盘件'), ('ELECTRIC', '电器件'), ('BODY', '外观件'), ('OIL', '油品'), ('OTHER', '其他')], default='OTHER', max_length=20)),
                ('spec', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(default='个', max_length=10)),
                ('stock_qty', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BOSS', '门店老板'), ('SALES', '配件销售'), ('WAREHOUSE', '库管')], default='SALES', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ReminderRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='inventory.collectionreminder')),
            ],
            options={
                'db_table': 'reminder_remark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', '现金'), ('BANK', '银行转账'), ('WECHAT', '微信'), ('ALIPAY', '支付宝'), ('CHECK', '支票')], default='BANK', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('REJECTED', '已驳回')], default='PENDING', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.order')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='inventory.order')),
            ],
            options={
                'db_table': 'order_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='inventory.order')),
            ],
            options={
                'db_table': 'order_remark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('part_code', models.CharField(max_length=50)),
                ('spec', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_quantity', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='inventory.order'),
        ),
    ]
