import type {
    Device,
    HistoryRemark,
    Material,
    RefundRequest,
    ScheduleItem,
    Station,
    StationMaterial,
    User,
    WorkOrder,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "张明",
    role: "supervisor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zhang",
  },
  {
    id: "u2",
    name: "李强",
    role: "inspector",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=li",
  },
  {
    id: "u3",
    name: "王芳",
    role: "inspector",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=wang",
  },
  {
    id: "u4",
    name: "赵丽",
    role: "customer_service",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zhao",
  },
];

export const mockStations: Station[] = [
  {
    id: "s1",
    name: "朝阳路自助洗车站",
    address: "北京市朝阳区朝阳路188号",
    status: "normal",
    deviceCount: 3,
    lastInspection: "2024-01-15",
    managerId: "u1",
  },
  {
    id: "s2",
    name: "海淀区中关村站",
    address: "北京市海淀区中关村大街23号",
    status: "warning",
    deviceCount: 4,
    lastInspection: "2024-01-14",
    managerId: "u1",
  },
  {
    id: "s3",
    name: "西城区金融街站",
    address: "北京市西城区金融街56号",
    status: "fault",
    deviceCount: 2,
    lastInspection: "2024-01-10",
    managerId: "u1",
  },
  {
    id: "s4",
    name: "东城区王府井站",
    address: "北京市东城区王府井大街88号",
    status: "maintenance",
    deviceCount: 3,
    lastInspection: "2024-01-16",
    managerId: "u1",
  },
];

export const mockDevices: Device[] = [
  {
    id: "d1",
    stationId: "s1",
    name: "高压水枪-A1",
    model: "HW-2024-Pro",
    status: "online",
    lastMaintenance: "2024-01-10",
    faultCount: 2,
  },
  {
    id: "d2",
    stationId: "s1",
    name: "泡沫机-A2",
    model: "FM-2024-Standard",
    status: "online",
    lastMaintenance: "2024-01-08",
    faultCount: 0,
  },
  {
    id: "d3",
    stationId: "s1",
    name: "吸尘器-A3",
    model: "VC-2024-Max",
    status: "fault",
    lastMaintenance: "2024-01-12",
    faultCount: 5,
  },
  {
    id: "d4",
    stationId: "s2",
    name: "高压水枪-B1",
    model: "HW-2024-Pro",
    status: "online",
    lastMaintenance: "2024-01-11",
    faultCount: 1,
  },
  {
    id: "d5",
    stationId: "s2",
    name: "高压水枪-B2",
    model: "HW-2024-Pro",
    status: "offline",
    lastMaintenance: "2024-01-05",
    faultCount: 3,
  },
  {
    id: "d6",
    stationId: "s3",
    name: "高压水枪-C1",
    model: "HW-2024-Pro",
    status: "fault",
    lastMaintenance: "2024-01-02",
    faultCount: 8,
  },
  {
    id: "d7",
    stationId: "s3",
    name: "泡沫机-C2",
    model: "FM-2024-Standard",
    status: "fault",
    lastMaintenance: "2024-01-01",
    faultCount: 4,
  },
  {
    id: "d8",
    stationId: "s4",
    name: "高压水枪-D1",
    model: "HW-2024-Pro",
    status: "maintenance",
    lastMaintenance: "2024-01-16",
    faultCount: 2,
  },
];

export const mockMaterials: Material[] = [
  {
    id: "m1",
    name: "高泡洗车液",
    sku: "SKU-SOAP-001",
    category: "soap",
    currentStock: 120,
    minStock: 30,
    unit: "L",
    status: "normal",
  },
  {
    id: "m2",
    name: "纳米镀膜蜡",
    sku: "SKU-WAX-002",
    category: "wax",
    currentStock: 15,
    minStock: 20,
    unit: "L",
    status: "low",
  },
  {
    id: "m3",
    name: "超细纤维毛巾",
    sku: "SKU-TOWEL-003",
    category: "towel",
    currentStock: 200,
    minStock: 50,
    unit: "条",
    status: "normal",
  },
  {
    id: "m4",
    name: "轮毂清洁刷",
    sku: "SKU-BRUSH-004",
    category: "brush",
    currentStock: 5,
    minStock: 10,
    unit: "个",
    status: "low",
  },
  {
    id: "m5",
    name: "玻璃清洁剂",
    sku: "SKU-OTHER-005",
    category: "other",
    currentStock: 0,
    minStock: 20,
    unit: "L",
    status: "out_of_stock",
  },
];

export const mockStationMaterials: StationMaterial[] = [
  { stationId: "s1", materialId: "m1", currentStock: 25, lastRestock: "2024-01-10" },
  { stationId: "s1", materialId: "m2", currentStock: 3, lastRestock: "2024-01-08" },
  { stationId: "s1", materialId: "m3", currentStock: 45, lastRestock: "2024-01-12" },
  { stationId: "s1", materialId: "m4", currentStock: 2, lastRestock: "2024-01-05" },
  { stationId: "s1", materialId: "m5", currentStock: 0, lastRestock: "2023-12-20" },
  { stationId: "s2", materialId: "m1", currentStock: 18, lastRestock: "2024-01-11" },
  { stationId: "s2", materialId: "m2", currentStock: 5, lastRestock: "2024-01-09" },
  { stationId: "s2", materialId: "m3", currentStock: 30, lastRestock: "2024-01-10" },
  { stationId: "s3", materialId: "m1", currentStock: 8, lastRestock: "2024-01-02" },
  { stationId: "s3", materialId: "m2", currentStock: 1, lastRestock: "2024-01-01" },
  { stationId: "s3", materialId: "m3", currentStock: 15, lastRestock: "2023-12-28" },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "wo1",
    type: "repair",
    title: "3号吸尘器吸力不足",
    description: "客户反映3号吸尘器吸力明显不足，无法清理车内灰尘",
    stationId: "s1",
    deviceId: "d3",
    priority: "high",
    status: "processing",
    creatorId: "u4",
    assigneeId: "u2",
    createdAt: "2024-01-16T09:30:00",
    updatedAt: "2024-01-16T14:20:00",
    history: [
      {
        status: "pending",
        operatorId: "u4",
        timestamp: "2024-01-16T09:30:00",
        remark: "客服赵丽接到客户投诉，创建工单",
      },
      {
        status: "assigned",
        operatorId: "u1",
        timestamp: "2024-01-16T10:00:00",
        remark: "主管张明派单给巡检员李强",
      },
      {
        status: "processing",
        operatorId: "u2",
        timestamp: "2024-01-16T14:20:00",
        remark: "李强已到达现场，开始检查设备",
      },
    ],
    attachments: [
      {
        id: "att1",
        type: "image",
        url: "https://picsum.photos/400/300?random=1",
        uploadedBy: "u4",
        uploadedAt: "2024-01-16T09:32:00",
        description: "客户提供的吸尘器工作视频截图",
      },
    ],
  },
  {
    id: "wo2",
    type: "restock",
    title: "玻璃清洁剂缺货",
    description: "朝阳路站玻璃清洁剂库存为0，需要紧急补货",
    stationId: "s1",
    materialId: "m5",
    priority: "urgent",
    status: "pending",
    creatorId: "u2",
    createdAt: "2024-01-16T11:00:00",
    updatedAt: "2024-01-16T11:00:00",
    history: [
      {
        status: "pending",
        operatorId: "u2",
        timestamp: "2024-01-16T11:00:00",
        remark: "巡检员李强盘点发现缺货，提交补货申请",
      },
    ],
    attachments: [
      {
        id: "att2",
        type: "image",
        url: "https://picsum.photos/400/300?random=2",
        uploadedBy: "u2",
        uploadedAt: "2024-01-16T11:05:00",
        description: "空货架照片",
      },
    ],
  },
  {
    id: "wo3",
    type: "repair",
    title: "1号高压水枪漏水",
    description: "设备启动后枪头处漏水严重，无法正常使用",
    stationId: "s3",
    deviceId: "d6",
    priority: "urgent",
    status: "reviewing",
    creatorId: "u4",
    assigneeId: "u3",
    createdAt: "2024-01-15T15:40:00",
    updatedAt: "2024-01-16T08:30:00",
    history: [
      {
        status: "pending",
        operatorId: "u4",
        timestamp: "2024-01-15T15:40:00",
        remark: "客服接到报修",
      },
      {
        status: "assigned",
        operatorId: "u1",
        timestamp: "2024-01-15T16:00:00",
        remark: "主管派单给王芳",
      },
      {
        status: "processing",
        operatorId: "u3",
        timestamp: "2024-01-15T17:00:00",
        remark: "王芳现场检查，发现密封圈损坏",
      },
      {
        status: "reviewing",
        operatorId: "u3",
        timestamp: "2024-01-16T08:30:00",
        remark: "已更换密封圈，申请审核",
      },
    ],
    attachments: [
      {
        id: "att3",
        type: "image",
        url: "https://picsum.photos/400/300?random=3",
        uploadedBy: "u3",
        uploadedAt: "2024-01-15T17:05:00",
        description: "漏水点特写照片",
      },
      {
        id: "att4",
        type: "image",
        url: "https://picsum.photos/400/300?random=4",
        uploadedBy: "u3",
        uploadedAt: "2024-01-16T08:35:00",
        description: "修复后测试照片",
      },
    ],
  },
  {
    id: "wo4",
    type: "complaint",
    title: "设备故障退款申请",
    description: "客户使用2号水枪时设备突然停机，要求全额退款30元",
    stationId: "s2",
    deviceId: "d5",
    priority: "high",
    status: "rejected",
    creatorId: "u4",
    assigneeId: "u1",
    createdAt: "2024-01-15T10:00:00",
    updatedAt: "2024-01-15T16:00:00",
    history: [
      {
        status: "pending",
        operatorId: "u4",
        timestamp: "2024-01-15T10:00:00",
        remark: "客服创建退款工单",
      },
      {
        status: "reviewing",
        operatorId: "u1",
        timestamp: "2024-01-15T14:00:00",
        remark: "主管审核中",
      },
      {
        status: "rejected",
        operatorId: "u1",
        timestamp: "2024-01-15T16:00:00",
        remark: "",
      },
    ],
    attachments: [
      {
        id: "att5",
        type: "text",
        url: "",
        uploadedBy: "u4",
        uploadedAt: "2024-01-15T10:05:00",
        description: "客户通话记录",
      },
    ],
    rejectInfo: {
      reason: "经核查设备日志，该设备在客户使用期间运行正常，无故障记录。可能为客户操作不当导致。",
      operatorId: "u1",
      timestamp: "2024-01-15T16:00:00",
      supplement: "建议客服引导客户正确使用设备，如再次遇到问题可联系现场巡检员",
    },
    refundAmount: 30,
    relatedOrderId: "ORD202401150001",
  },
  {
    id: "wo5",
    type: "inspection",
    title: "王府井站例行巡检",
    description: "每月例行设备巡检和耗材盘点",
    stationId: "s4",
    priority: "medium",
    status: "completed",
    creatorId: "u1",
    assigneeId: "u2",
    createdAt: "2024-01-14T09:00:00",
    updatedAt: "2024-01-16T12:00:00",
    completedAt: "2024-01-16T12:00:00",
    history: [
      {
        status: "pending",
        operatorId: "u1",
        timestamp: "2024-01-14T09:00:00",
        remark: "主管创建月度巡检计划",
      },
      {
        status: "assigned",
        operatorId: "u1",
        timestamp: "2024-01-14T09:05:00",
        remark: "分配给李强",
      },
      {
        status: "processing",
        operatorId: "u2",
        timestamp: "2024-01-16T09:00:00",
        remark: "开始巡检",
      },
      {
        status: "completed",
        operatorId: "u2",
        timestamp: "2024-01-16T12:00:00",
        remark: "巡检完成，所有设备正常",
      },
    ],
    attachments: [
      {
        id: "att6",
        type: "image",
        url: "https://picsum.photos/400/300?random=6",
        uploadedBy: "u2",
        uploadedAt: "2024-01-16T10:00:00",
        description: "设备整体照片",
      },
      {
        id: "att7",
        type: "image",
        url: "https://picsum.photos/400/300?random=7",
        uploadedBy: "u2",
        uploadedAt: "2024-01-16T11:00:00",
        description: "耗材库存照片",
      },
    ],
  },
  {
    id: "wo6",
    type: "restock",
    title: "纳米镀膜蜡库存预警",
    description: "中关村站纳米镀膜蜡库存低于安全线",
    stationId: "s2",
    materialId: "m2",
    priority: "medium",
    status: "assigned",
    creatorId: "u1",
    assigneeId: "u3",
    createdAt: "2024-01-16T08:00:00",
    updatedAt: "2024-01-16T08:30:00",
    history: [
      {
        status: "pending",
        operatorId: "u1",
        timestamp: "2024-01-16T08:00:00",
        remark: "系统自动触发库存预警",
      },
      {
        status: "assigned",
        operatorId: "u1",
        timestamp: "2024-01-16T08:30:00",
        remark: "主管派单给王芳处理补货",
      },
    ],
    attachments: [],
  },
  {
    id: "wo7",
    type: "repair",
    title: "2号水枪压力不稳定",
    description: "客户投诉水压忽大忽小，影响使用体验",
    stationId: "s2",
    deviceId: "d5",
    priority: "high",
    status: "escalated",
    creatorId: "u4",
    assigneeId: "u1",
    createdAt: "2024-01-16T13:00:00",
    updatedAt: "2024-01-16T15:00:00",
    history: [
      {
        status: "pending",
        operatorId: "u4",
        timestamp: "2024-01-16T13:00:00",
        remark: "客服接到投诉，3天内已收到5次相同投诉",
      },
      {
        status: "assigned",
        operatorId: "u1",
        timestamp: "2024-01-16T13:30:00",
        remark: "分配给李强处理",
      },
      {
        status: "escalated",
        operatorId: "u2",
        timestamp: "2024-01-16T15:00:00",
        remark: "经检查为水泵内部故障，需要联系厂家更换配件，已升级处理",
      },
    ],
    attachments: [
      {
        id: "att8",
        type: "image",
        url: "https://picsum.photos/400/300?random=8",
        uploadedBy: "u2",
        uploadedAt: "2024-01-16T14:30:00",
        description: "水泵故障部位照片",
      },
    ],
  },
];

export const mockRefundRequests: RefundRequest[] = [
  {
    id: "rf1",
    workOrderId: "wo4",
    orderId: "ORD202401150001",
    customerName: "陈先生",
    customerPhone: "138****5678",
    amount: 30,
    reason: "设备突然停机，未完成洗车",
    evidence: "客户通话记录 + 支付截图",
    status: "rejected",
    createdBy: "u4",
    reviewedBy: "u1",
    reviewedAt: "2024-01-15T16:00:00",
  },
  {
    id: "rf2",
    workOrderId: "wo3",
    orderId: "ORD202401150002",
    customerName: "刘女士",
    customerPhone: "139****1234",
    amount: 25,
    reason: "水枪漏水，衣服被打湿",
    evidence: "现场照片 + 通话录音",
    status: "approved",
    createdBy: "u4",
    reviewedBy: "u1",
    reviewedAt: "2024-01-15T18:00:00",
    transferedAt: "2024-01-15T18:30:00",
  },
  {
    id: "rf3",
    workOrderId: "wo1",
    orderId: "ORD202401160001",
    customerName: "周先生",
    customerPhone: "137****8899",
    amount: 15,
    reason: "吸尘器无法使用，未清理车内",
    evidence: "客户提供的视频",
    status: "pending",
    createdBy: "u4",
  },
];

export const mockScheduleItems: ScheduleItem[] = [
  {
    id: "sch1",
    inspectorId: "u2",
    stationId: "s1",
    date: "2024-01-17",
    timeSlot: "09:00-12:00",
    tasks: ["设备巡检", "耗材盘点"],
    status: "pending",
    workOrderIds: ["wo1", "wo2"],
  },
  {
    id: "sch2",
    inspectorId: "u3",
    stationId: "s2",
    date: "2024-01-17",
    timeSlot: "09:00-12:00",
    tasks: ["设备检修", "耗材补货"],
    status: "pending",
    workOrderIds: ["wo6", "wo7"],
  },
  {
    id: "sch3",
    inspectorId: "u2",
    stationId: "s3",
    date: "2024-01-17",
    timeSlot: "14:00-17:00",
    tasks: ["设备维修", "耗材盘点"],
    status: "pending",
    workOrderIds: ["wo3"],
  },
  {
    id: "sch4",
    inspectorId: "u3",
    stationId: "s4",
    date: "2024-01-17",
    timeSlot: "14:00-17:00",
    tasks: ["例行巡检"],
    status: "pending",
    workOrderIds: [],
  },
  {
    id: "sch5",
    inspectorId: "u2",
    stationId: "s1",
    date: "2024-01-16",
    timeSlot: "14:00-17:00",
    tasks: ["设备维修"],
    status: "in_progress",
    workOrderIds: ["wo1"],
  },
];

export const mockHistoryRemarks: HistoryRemark[] = [
  {
    id: "hr1",
    workOrderId: "wo1",
    content: "客户情绪比较激动，已安抚，承诺48小时内解决",
    authorId: "u4",
    createdAt: "2024-01-16T09:35:00",
    type: "manual",
  },
  {
    id: "hr2",
    workOrderId: "wo1",
    content: "现场检查发现进风口被异物堵塞，已清理，正在测试吸力",
    authorId: "u2",
    createdAt: "2024-01-16T14:35:00",
    type: "manual",
  },
  {
    id: "hr3",
    workOrderId: "wo4",
    content: "客户表示不接受驳回结果，要求升级处理，请主管关注",
    authorId: "u4",
    createdAt: "2024-01-15T17:00:00",
    type: "manual",
  },
  {
    id: "hr4",
    workOrderId: "wo7",
    content: "该设备在半年内已发生3次相同故障，建议列入重点监控名单",
    authorId: "u2",
    createdAt: "2024-01-16T15:10:00",
    type: "manual",
  },
];
