export enum Role {
  STORE_OWNER = 'STORE_OWNER',
  RENTAL_ADVISOR = 'RENTAL_ADVISOR',
  MAINTENANCE_TECH = 'MAINTENANCE_TECH',
}

export enum InstrumentStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  IN_MAINTENANCE = 'IN_MAINTENANCE',
  DAMAGED = 'DAMAGED',
  RETIRED = 'RETIRED',
}

export enum RentalStatus {
  ACTIVE = 'ACTIVE',
  RETURNED = 'RETURNED',
  SETTLED = 'SETTLED',
  OVERDUE = 'OVERDUE',
}

export enum DepositStatus {
  HELD = 'HELD',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  PARTIAL_REFUNDED = 'PARTIAL_REFUNDED',
  DEDUCTED = 'DEDUCTED',
  DISPUTED = 'DISPUTED',
}

export enum DamageClaimStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  DISPUTED = 'DISPUTED',
  REJECTED = 'REJECTED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum DamageSeverity {
  MINOR = 'MINOR',
  MODERATE = 'MODERATE',
  MAJOR = 'MAJOR',
  TOTAL = 'TOTAL',
}

export enum AuditAction {
  RENTAL_CREATE = 'RENTAL_CREATE',
  RENTAL_RETURN = 'RENTAL_RETURN',
  RENTAL_EXTEND = 'RENTAL_EXTEND',
  RENTAL_CANCEL = 'RENTAL_CANCEL',
  DEPOSIT_SETTLE = 'DEPOSIT_SETTLE',
  DEPOSIT_REFUND = 'DEPOSIT_REFUND',
  DEPOSIT_DEDUCT = 'DEPOSIT_DEDUCT',
  DEPOSIT_PARTIAL_REFUND = 'DEPOSIT_PARTIAL_REFUND',
  DEPOSIT_DISPUTE = 'DEPOSIT_DISPUTE',
  DAMAGE_REPORT = 'DAMAGE_REPORT',
  DAMAGE_CONFIRM = 'DAMAGE_CONFIRM',
  DAMAGE_DISPUTE = 'DAMAGE_DISPUTE',
  DAMAGE_REJECT = 'DAMAGE_REJECT',
  DAMAGE_RESOLVE = 'DAMAGE_RESOLVE',
  DAMAGE_CLOSE = 'DAMAGE_CLOSE',
  MAINTENANCE_CREATE = 'MAINTENANCE_CREATE',
  MAINTENANCE_COMPLETE = 'MAINTENANCE_COMPLETE',
  MAINTENANCE_UPDATE = 'MAINTENANCE_UPDATE',
  NOTE_ADD = 'NOTE_ADD',
  NOTE_SUPPLEMENT = 'NOTE_SUPPLEMENT',
  STATUS_CHANGE = 'STATUS_CHANGE',
  DATA_EDIT = 'DATA_EDIT',
  DATA_DELETE = 'DATA_DELETE',
}

export enum EntityType {
  RENTAL = 'RENTAL',
  DEPOSIT = 'DEPOSIT',
  DAMAGE_CLAIM = 'DAMAGE_CLAIM',
  MAINTENANCE = 'MAINTENANCE',
  INSTRUMENT = 'INSTRUMENT',
}

export enum MaintenanceStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
