const Role = {
  THEATER_MANAGER: 'THEATER_MANAGER',
  TICKET_SUPERVISOR: 'TICKET_SUPERVISOR',
  BACKEND_COORDINATOR: 'BACKEND_COORDINATOR',
};

const ScheduleStatus = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PERFORMING: 'PERFORMING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED',
};

const EquipmentBorrowStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  BORROWED: 'BORROWED',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE',
};

const ReviewIssueStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

const GroupOrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const AuditAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  REMARK: 'REMARK',
  SUPPLEMENT: 'SUPPLEMENT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

const EntityType = {
  SCHEDULE: 'SCHEDULE',
  EQUIPMENT: 'EQUIPMENT',
  EQUIPMENT_BORROW: 'EQUIPMENT_BORROW',
  PERFORMANCE_REVIEW: 'PERFORMANCE_REVIEW',
  REVIEW_ISSUE: 'REVIEW_ISSUE',
  GROUP_ORDER: 'GROUP_ORDER',
  USER: 'USER',
};

module.exports = {
  Role,
  ScheduleStatus,
  EquipmentBorrowStatus,
  ReviewIssueStatus,
  GroupOrderStatus,
  AuditAction,
  EntityType,
};
