# Generated by Django 4.2.30 on 2026-05-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_type', models.CharField(choices=[('group', '大班课'), ('small_group', '小班课'), ('private', '私教课')], max_length=20, verbose_name='课程类型')),
                ('level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '高级')], max_length=20, verbose_name='难度等级')),
                ('duration', models.IntegerField(verbose_name='课时(分钟)')),
                ('max_students', models.IntegerField(default=10, verbose_name='最大人数')),
                ('min_students', models.IntegerField(default=1, verbose_name='最少人数')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('requirements', models.TextField(blank=True, verbose_name='学员要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程模板',
                'verbose_name_plural': '课程模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学员姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话')),
                ('health_notes', models.TextField(blank=True, verbose_name='健康备注')),
                ('swim_level', models.CharField(blank=True, choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '高级')], max_length=20, verbose_name='当前水平')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'phone'], name='schedule_st_name_6a2d9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('pool_lane', models.CharField(blank=True, max_length=50, verbose_name='泳道')),
                ('status', models.CharField(choices=[('draft', '待发布'), ('published', '已发布'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('max_students', models.IntegerField(verbose_name='最大人数')),
                ('actual_students', models.IntegerField(default=0, verbose_name='实际人数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.PROTECT, related_name='coached_schedules', to=settings.AUTH_USER_MODEL, verbose_name='教练')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='schedule.course', verbose_name='课程')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '已报名'), ('attended', '已上课'), ('absent', '缺勤'), ('leave_approved', '请假批准'), ('leave_rejected', '请假驳回'), ('cancelled', '已取消')], default='enrolled', max_length=20, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('attendance_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('leave_reason', models.TextField(blank=True, verbose_name='请假原因')),
                ('leave_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='请假审批时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('leave_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='请假审批人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schedule.schedule', verbose_name='排班')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schedule.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_time', 'status'], name='schedule_sc_start_t_c644a4_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['coach', 'start_time'], name='schedule_sc_coach_i_7a9c59_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['schedule', 'status'], name='schedule_en_schedul_3dd3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='schedule_en_student_60dc59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('schedule', 'student')},
        ),
    ]
