# Generated by Django 4.2.30 on 2026-05-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='卡号')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('remaining_times', models.IntegerField(blank=True, null=True, verbose_name='剩余次数')),
                ('start_date', models.DateField(verbose_name='生效日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '已冻结'), ('expired', '已过期'), ('cancelled', '已注销')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '储值卡',
                'verbose_name_plural': '储值卡',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('plan_type', models.CharField(choices=[('prepaid', '储值卡'), ('times', '次卡'), ('duration', '期卡')], max_length=20, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='卡内价值')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='次数(次卡)')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='有效期天数(期卡)')),
                ('description', models.TextField(blank=True, verbose_name='套餐说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在售')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '储值套餐',
                'verbose_name_plural': '储值套餐',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额')),
                ('value_added', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='到账金额')),
                ('times_added', models.IntegerField(blank=True, null=True, verbose_name='增加次数')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank', '银行卡'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('transaction_no', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharges', to='membership.membershipcard', verbose_name='储值卡')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_recharges', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershipplan', verbose_name='充值套餐')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='membership.membershipplan', verbose_name='套餐'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='schedule.student', verbose_name='学员'),
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_type', models.CharField(choices=[('course', '课程消费'), ('product', '商品购买'), ('service', '其他服务')], max_length=20, verbose_name='消费类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费金额')),
                ('times_deducted', models.IntegerField(blank=True, null=True, verbose_name='扣减次数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='membership.membershipcard', verbose_name='储值卡')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('related_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='schedule.enrollment', verbose_name='关联报名')),
                ('related_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='schedule.schedule', verbose_name='关联排班')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershipcard',
            index=models.Index(fields=['card_number'], name='membership__card_nu_1660e2_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipcard',
            index=models.Index(fields=['student', 'status'], name='membership__student_be9c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumptionrecord',
            index=models.Index(fields=['membership', 'created_at'], name='membership__members_0d23a1_idx'),
        ),
        migrations.AddIndex(
            model_name='consumptionrecord',
            index=models.Index(fields=['related_schedule'], name='membership__related_944ade_idx'),
        ),
    ]
