import type {
  User,
  Order,
  ProductionSchedule,
  CapacityConfig,
  Communication,
} from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: '林店长',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: 'user-2',
    name: '张主厨',
    role: 'chef',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: 'user-3',
    name: '王客服',
    role: 'customer_service',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100&h=100',
  },
];

const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const dayAfter = new Date(today);
dayAfter.setDate(dayAfter.getDate() + 2);

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNo: 'BK20250531001',
    customerName: '李女士',
    customerPhone: '138****1234',
    items: [
      {
        id: 'item-1',
        productName: '生日蛋糕（6寸）',
        quantity: 1,
        unitPrice: 298,
        specifications: '草莓慕斯，低糖配方',
      },
      {
        id: 'item-2',
        productName: '奶油泡芙',
        quantity: 12,
        unitPrice: 8,
        specifications: '香草馅',
      },
    ],
    totalAmount: 394,
    deposit: 200,
    pickupTime: tomorrow.toISOString().split('T')[0] + ' 15:00',
    status: 'pending_review',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    createdBy: 'user-3',
    notes: '客户是老顾客，希望能多送两个小饼干',
    history: [
      {
        id: 'h-1',
        orderId: 'order-1',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '客户通过微信预订',
      },
    ],
    isUrgent: false,
    isOverdue: false,
  },
  {
    id: 'order-2',
    orderNo: 'BK20250531002',
    customerName: '王先生',
    customerPhone: '139****5678',
    items: [
      {
        id: 'item-3',
        productName: '婚礼蛋糕（10寸）',
        quantity: 1,
        unitPrice: 888,
        specifications: '双层，玫瑰装饰',
      },
    ],
    totalAmount: 888,
    deposit: 500,
    pickupTime: today.toISOString().split('T')[0] + ' 10:00',
    status: 'change_requested',
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '原订单是后天取，客户刚打电话说要改到明天',
    history: [
      {
        id: 'h-2',
        orderId: 'order-2',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '婚礼订单，需提前准备',
      },
      {
        id: 'h-3',
        orderId: 'order-2',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '同意接单',
      },
      {
        id: 'h-4',
        orderId: 'order-2',
        action: '安排排期',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '安排在后天上午生产',
      },
    ],
    isUrgent: true,
    isOverdue: false,
    changeRequest: {
      id: 'cr-1',
      orderId: 'order-2',
      requestedBy: 'user-3',
      requestedAt: today.toISOString(),
      reason: '客户婚期提前，需要改取货时间',
      changes: [
        {
          field: 'pickupTime',
          oldValue: dayAfter.toISOString().split('T')[0] + ' 10:00',
          newValue: tomorrow.toISOString().split('T')[0] + ' 10:00',
        },
      ],
      status: 'pending',
    },
  },
  {
    id: 'order-3',
    orderNo: 'BK20250531003',
    customerName: '陈女士',
    customerPhone: '137****9012',
    items: [
      {
        id: 'item-4',
        productName: '全麦吐司',
        quantity: 2,
        unitPrice: 38,
        specifications: '无糖',
      },
      {
        id: 'item-5',
        productName: '可颂面包',
        quantity: 6,
        unitPrice: 12,
        specifications: '原味',
      },
    ],
    totalAmount: 148,
    deposit: 50,
    pickupTime: yesterday.toISOString().split('T')[0] + ' 18:00',
    status: 'scheduled',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '',
    history: [
      {
        id: 'h-5',
        orderId: 'order-3',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '到店自提',
      },
      {
        id: 'h-6',
        orderId: 'order-3',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '同意',
      },
    ],
    isUrgent: false,
    isOverdue: true,
  },
  {
    id: 'order-4',
    orderNo: 'BK20250531004',
    customerName: '赵先生',
    customerPhone: '136****3456',
    items: [
      {
        id: 'item-6',
        productName: '宝宝百日蛋糕',
        quantity: 1,
        unitPrice: 398,
        specifications: '8寸，芒果夹心',
      },
      {
        id: 'item-7',
        productName: '曲奇礼盒',
        quantity: 2,
        unitPrice: 88,
        specifications: '混合口味',
      },
    ],
    totalAmount: 574,
    deposit: 300,
    pickupTime: dayAfter.toISOString().split('T')[0] + ' 14:00',
    status: 'refund_requested',
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '客户说宝宝生病了，百日宴取消',
    history: [
      {
        id: 'h-7',
        orderId: 'order-4',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '宝宝百日宴订单',
      },
      {
        id: 'h-8',
        orderId: 'order-4',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '同意接单',
      },
      {
        id: 'h-9',
        orderId: 'order-4',
        action: '安排排期',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '已采购芒果原料',
      },
    ],
    isUrgent: false,
    isOverdue: false,
    refundRequest: {
      id: 'rf-1',
      orderId: 'order-4',
      requestedBy: 'user-3',
      requestedAt: today.toISOString(),
      reason: '宝宝生病，百日宴取消',
      refundAmount: 250,
      status: 'pending',
    },
  },
  {
    id: 'order-5',
    orderNo: 'BK20250531005',
    customerName: '孙女士',
    customerPhone: '135****7890',
    items: [
      {
        id: 'item-8',
        productName: '牛角包套餐',
        quantity: 5,
        unitPrice: 25,
        specifications: '原味+巧克力',
      },
    ],
    totalAmount: 125,
    deposit: 50,
    pickupTime: today.toISOString().split('T')[0] + ' 09:00',
    status: 'in_production',
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '公司早餐订单',
    history: [
      {
        id: 'h-10',
        orderId: 'order-5',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '公司团购',
      },
      {
        id: 'h-11',
        orderId: 'order-5',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '同意',
      },
      {
        id: 'h-12',
        orderId: 'order-5',
        action: '安排排期',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '今早6点开始制作',
      },
      {
        id: 'h-13',
        orderId: 'order-5',
        action: '开始生产',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: today.toISOString(),
        remarks: '正在制作中',
      },
    ],
    isUrgent: true,
    isOverdue: false,
  },
  {
    id: 'order-6',
    orderNo: 'BK20250531006',
    customerName: '周先生',
    customerPhone: '134****2345',
    items: [
      {
        id: 'item-9',
        productName: '抹茶千层',
        quantity: 1,
        unitPrice: 168,
        specifications: '6寸',
      },
    ],
    totalAmount: 168,
    deposit: 80,
    pickupTime: yesterday.toISOString().split('T')[0] + ' 16:00',
    status: 'completed',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '',
    history: [
      {
        id: 'h-14',
        orderId: 'order-6',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-15',
        orderId: 'order-6',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-16',
        orderId: 'order-6',
        action: '安排排期',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-17',
        orderId: 'order-6',
        action: '开始生产',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-18',
        orderId: 'order-6',
        action: '完成交付',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '客户已取货，满意',
      },
    ],
    isUrgent: false,
    isOverdue: false,
  },
  {
    id: 'order-7',
    orderNo: 'BK20250531007',
    customerName: '吴女士',
    customerPhone: '133****6789',
    items: [
      {
        id: 'item-10',
        productName: '芝士蛋糕',
        quantity: 2,
        unitPrice: 128,
        specifications: '重芝士',
      },
    ],
    totalAmount: 256,
    deposit: 120,
    pickupTime: tomorrow.toISOString().split('T')[0] + ' 11:00',
    status: 'scheduled',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    createdBy: 'user-3',
    assignedChef: 'user-2',
    notes: '',
    history: [
      {
        id: 'h-19',
        orderId: 'order-7',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-20',
        orderId: 'order-7',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
      {
        id: 'h-21',
        orderId: 'order-7',
        action: '安排排期',
        operator: '张主厨',
        operatorRole: 'chef',
        timestamp: yesterday.toISOString(),
        remarks: '',
      },
    ],
    isUrgent: false,
    isOverdue: false,
  },
  {
    id: 'order-8',
    orderNo: 'BK20250531008',
    customerName: '郑先生',
    customerPhone: '132****0123',
    items: [
      {
        id: 'item-11',
        productName: '蛋黄酥礼盒',
        quantity: 3,
        unitPrice: 68,
        specifications: '6枚装',
      },
    ],
    totalAmount: 204,
    deposit: 100,
    pickupTime: dayAfter.toISOString().split('T')[0] + ' 15:00',
    status: 'reviewed',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    createdBy: 'user-3',
    notes: '客户要求礼盒包装要精致',
    history: [
      {
        id: 'h-22',
        orderId: 'order-8',
        action: '创建订单',
        operator: '王客服',
        operatorRole: 'customer_service',
        timestamp: today.toISOString(),
        remarks: '端午节送礼',
      },
      {
        id: 'h-23',
        orderId: 'order-8',
        action: '审核通过',
        operator: '林店长',
        operatorRole: 'manager',
        timestamp: today.toISOString(),
        remarks: '同意接单',
      },
    ],
    isUrgent: false,
    isOverdue: false,
  },
];

export const mockSchedules: ProductionSchedule[] = [
  {
    id: 'sch-1',
    date: today.toISOString().split('T')[0],
    orderId: 'order-5',
    chefId: 'user-2',
    startTime: '06:00',
    endTime: '08:00',
    status: 'in_progress',
  },
  {
    id: 'sch-2',
    date: today.toISOString().split('T')[0],
    orderId: 'order-3',
    chefId: 'user-2',
    startTime: '09:00',
    endTime: '11:00',
    status: 'scheduled',
  },
  {
    id: 'sch-3',
    date: tomorrow.toISOString().split('T')[0],
    orderId: 'order-1',
    chefId: 'user-2',
    startTime: '10:00',
    endTime: '12:00',
    status: 'scheduled',
  },
  {
    id: 'sch-4',
    date: tomorrow.toISOString().split('T')[0],
    orderId: 'order-7',
    chefId: 'user-2',
    startTime: '13:00',
    endTime: '15:00',
    status: 'scheduled',
  },
  {
    id: 'sch-5',
    date: dayAfter.toISOString().split('T')[0],
    orderId: 'order-4',
    chefId: 'user-2',
    startTime: '08:00',
    endTime: '11:00',
    status: 'scheduled',
  },
  {
    id: 'sch-6',
    date: dayAfter.toISOString().split('T')[0],
    orderId: 'order-8',
    chefId: 'user-2',
    startTime: '14:00',
    endTime: '16:00',
    status: 'scheduled',
  },
];

export const mockCapacityConfigs: CapacityConfig[] = [
  {
    date: today.toISOString().split('T')[0],
    maxDailyOrders: 5,
    chefCapacities: {
      'user-2': 3,
    },
  },
  {
    date: tomorrow.toISOString().split('T')[0],
    maxDailyOrders: 5,
    chefCapacities: {
      'user-2': 3,
    },
  },
  {
    date: dayAfter.toISOString().split('T')[0],
    maxDailyOrders: 5,
    chefCapacities: {
      'user-2': 3,
    },
  },
];

export const mockCommunications: Communication[] = [
  {
    id: 'comm-1',
    orderId: 'order-2',
    sender: '王客服',
    senderRole: 'customer_service',
    content: '客户刚刚来电，婚期提前了一天，取货时间需要从后天改到明天上午10点。请问后厨能调整吗？原料已经采购了吗？',
    timestamp: today.toISOString(),
    type: 'internal',
  },
  {
    id: 'comm-2',
    orderId: 'order-2',
    sender: '张主厨',
    senderRole: 'chef',
    content: '我看看排期...明天上午已经有两个订单了，这个是大蛋糕，需要3个小时。如果改到明天下午可能可以，但客户要上午10点取的话有点紧张。原料还没开始做，只是采购了奶油。',
    timestamp: today.toISOString(),
    type: 'internal',
  },
  {
    id: 'comm-3',
    orderId: 'order-4',
    sender: '王客服',
    senderRole: 'customer_service',
    content: '客户来电话说宝宝发烧住院了，百日宴取消了，要申请退款。说是已经买了芒果，能不能只退押金的一部分？',
    timestamp: today.toISOString(),
    type: 'internal',
  },
  {
    id: 'comm-4',
    orderId: 'order-3',
    sender: '林店长',
    senderRole: 'manager',
    content: '这个订单昨天就应该取的，客户怎么还没来？客服联系一下客户，问问是什么情况。',
    timestamp: today.toISOString(),
    type: 'internal',
  },
];

export const testAccounts = {
  manager: { username: 'manager', password: '123456', name: '林店长' },
  chef: { username: 'chef', password: '123456', name: '张主厨' },
  customer_service: {
    username: 'service',
    password: '123456',
    name: '王客服',
  },
};
