from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=128, verbose_name='品名')),
                ('category', models.CharField(choices=[('green', '绿茶'), ('black', '红茶'), ('oolong', '乌龙茶'), ('white', '白茶'), ('dark', '黑茶'), ('other', '其他')], max_length=16, verbose_name='品类')),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础单价')),
                ('unit', models.CharField(default='斤', max_length=16, verbose_name='计量单位')),
                ('spec', models.CharField(blank=True, default='', max_length=128, verbose_name='规格说明')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=16, verbose_name='状态')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('region', models.CharField(choices=[('north', '华北'), ('east', '华东'), ('south', '华南'), ('west', '华西')], max_length=16, verbose_name='区域')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓库主管')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='门店编码')),
                ('name', models.CharField(max_length=64, verbose_name='门店名称')),
                ('region', models.CharField(choices=[('north', '华北'), ('east', '华东'), ('south', '华南'), ('west', '华西')], max_length=16, verbose_name='区域')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('responsible_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='tea.warehouse', verbose_name='负责仓库')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_no', models.CharField(max_length=32, unique=True, verbose_name='批次号')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='初始数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单位成本')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('partial', '部分出库'), ('depleted', '已出清')], default='in_stock', max_length=16, verbose_name='状态')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tea.product', verbose_name='产品')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tea.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_name', models.CharField(max_length=64, verbose_name='模型名称')),
                ('record_id', models.CharField(max_length=32, verbose_name='记录ID')),
                ('record_code', models.CharField(blank=True, default='', max_length=64, verbose_name='记录单号')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('APPROVE', '审批通过'), ('REJECT', '驳回'), ('SUBMIT', '提交'), ('CANCEL', '取消'), ('SHIP', '发货'), ('RECEIVE', '签收'), ('CONFIRM', '确认')], max_length=16, verbose_name='操作')),
                ('field_name', models.CharField(blank=True, default='', max_length=64, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditlog_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditlog_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('change_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('adjust', '盘点调整'), ('loss', '损耗'), ('return', '退货入库')], max_length=16, verbose_name='变动类型')),
                ('direction', models.SmallIntegerField(choices=[(1, '增加'), (-1, '减少')], verbose_name='方向')),
                ('change_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动数量')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动后结存')),
                ('reference_type', models.CharField(choices=[('shipment', '发货单'), ('order', '订货单'), ('inventory_check', '盘点单'), ('manual', '手工录入')], default='manual', max_length=16, verbose_name='来源类型')),
                ('reference_id', models.CharField(blank=True, default='', max_length=64, verbose_name='来源单号')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='tea.batch', verbose_name='批次')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryrecord_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryrecord_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '库存变动记录',
                'verbose_name_plural': '库存变动记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='审批单号')),
                ('proposed_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申报单价')),
                ('effective_from', models.DateField(verbose_name='生效起始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='生效截止日')),
                ('reason', models.TextField(verbose_name='调价原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_price_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceapproval_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_approvals', to='tea.product', verbose_name='产品')),
                ('store', models.ForeignKey(blank=True, help_text='为空表示全部门店通用', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.store', verbose_name='指定门店')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_price_approvals', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceapproval_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '价格审批',
                'verbose_name_plural': '价格审批',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_price', '可以审批价格'), ('can_submit_price', '可以提交价格审批')],
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='活动单号')),
                ('activity_type', models.CharField(choices=[('new_product', '新品推广'), ('festival', '节日促销'), ('trial', '试饮活动'), ('discount', '满减折扣'), ('bundle', '捆绑销售'), ('other', '其他')], max_length=16, verbose_name='活动类型')),
                ('activity_name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('activity_period_from', models.DateField(verbose_name='活动开始日')),
                ('activity_period_to', models.DateField(verbose_name='活动结束日')),
                ('target_sales_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='目标销量')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='活动预算')),
                ('description', models.TextField(blank=True, default='', verbose_name='活动说明')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='回查备注')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitysubmission_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('price_approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tea.priceapproval', verbose_name='关联价格审批')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_activities', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitysubmission_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '活动提报',
                'verbose_name_plural': '活动提报',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_activity', '可以审批活动'), ('can_submit_activity', '可以提交活动')],
            },
        ),
        migrations.CreateModel(
            name='TrialFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='回访单号')),
                ('visit_date', models.DateField(verbose_name='回访日期')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='反馈内容')),
                ('sample_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='试饮数量')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='下次回访日')),
                ('result', models.CharField(choices=[('excellent', '满意'), ('normal', '一般'), ('poor', '不满意')], max_length=16, verbose_name='回访结果')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_followups', to='tea.activitysubmission', verbose_name='关联活动')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trialfollowup_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_followups', to='tea.store', verbose_name='门店')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trialfollowup_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '试饮回访',
                'verbose_name_plural': '试饮回访',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='订货单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('shipped', '已发货'), ('received', '已签收'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('activity', models.ForeignKey(blank=True, help_text='关联活动后将自动使用活动价', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tea.activitysubmission', verbose_name='关联活动')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tea.store', verbose_name='门店')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_orders', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '订货单',
                'verbose_name_plural': '订货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='发货单号')),
                ('tracking_no', models.CharField(blank=True, default='', max_length=64, verbose_name='物流单号')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('received', '已签收'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_shipments', to='tea.warehouse', verbose_name='发货仓库')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tea.order', verbose_name='订货单')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shipped_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='发货数量')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='tea.batch', verbose_name='实际批次')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipmentitem_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='tea.orderitem', verbose_name='订货物料')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tea.shipment', verbose_name='发货单')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipmentitem_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '发货明细',
                'verbose_name_plural': '发货明细',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('activity_price_applied', models.BooleanField(default=False, verbose_name='使用活动价')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='tea.batch', verbose_name='指定批次')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tea.order', verbose_name='订货单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tea.product', verbose_name='产品')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '订货物料',
                'verbose_name_plural': '订货物料',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='tea_auditlo_model_n_b6d7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='tea_auditlo_action_008a14_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='tea_auditlo_created_f7df2e_idx'),
        ),
    ]
