# Generated by Django 4.2.30 on 2026-05-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_schedules', models.IntegerField(default=0, verbose_name='总排数')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='总报名数')),
                ('attended_count', models.IntegerField(default=0, verbose_name='出勤数')),
                ('absent_count', models.IntegerField(default=0, verbose_name='缺勤数')),
                ('leave_count', models.IntegerField(default=0, verbose_name='请假数')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='出勤率%')),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='消课总额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考勤汇总',
                'verbose_name_plural': '考勤汇总',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='对账开始日期')),
                ('end_date', models.DateField(verbose_name='对账结束日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_schedules', models.IntegerField(default=0, verbose_name='总排数')),
                ('processed_schedules', models.IntegerField(default=0, verbose_name='已处理数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='对账总金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '对账批次',
                'verbose_name_plural': '对账批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '已跳过')], max_length=20, verbose_name='状态')),
                ('total_students', models.IntegerField(default=0, verbose_name='学员总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_details', models.TextField(blank=True, verbose_name='错误详情')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.reconciliationbatch', verbose_name='对账批次')),
            ],
            options={
                'verbose_name': '对账记录',
                'verbose_name_plural': '对账记录',
                'ordering': ['-processed_at'],
            },
        ),
    ]
