# Generated by Django 4.2.30 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('skipped', '已跳过')], max_length=20, verbose_name='状态'),
        ),
    ]
