# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('approve', '审批'), ('reject', '驳回'), ('assign', '分配'), ('complete', '完成'), ('other', '其他')], default='other', max_length=50, verbose_name='操作类型')),
                ('module', models.CharField(max_length=100, verbose_name='操作模块')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='对象表示')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('message', models.TextField(blank=True, verbose_name='操作描述')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='变更字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功'), ('urgent', '紧急')], default='info', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='关联模块')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='关联对象ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='是否紧急')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverdueReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('repair', '报修逾期'), ('inspection', '巡检逾期'), ('borrow', '借阅逾期'), ('activity', '活动待确认')], max_length=30, verbose_name='提醒类型')),
                ('related_object_id', models.CharField(max_length=100, verbose_name='关联对象ID')),
                ('related_object_repr', models.CharField(max_length=200, verbose_name='关联对象')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('reminder_count', models.IntegerField(default=1, verbose_name='提醒次数')),
                ('last_reminder_at', models.DateTimeField(auto_now_add=True, verbose_name='上次提醒时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '逾期提醒',
                'verbose_name_plural': '逾期提醒',
                'db_table': 'overdue_reminders',
                'ordering': ['-created_at'],
            },
        ),
    ]
