import type {
  Equipment,
  BorrowRecord,
  ReturnInspection,
  Booking,
  StoredValueRecord,
  ReviewCase,
  DashboardStats,
  User,
} from "@/types";

export const mockUsers: User[] = [
  { id: "u1", name: "张前台", role: "reception" },
  { id: "u2", name: "李教练", role: "coach" },
  { id: "u3", name: "王经理", role: "manager" },
];

export const mockEquipment: Equipment[] = [
  {
    id: "e1",
    name: "Titleist 一号木",
    category: "club",
    brand: "Titleist",
    model: "TSR3",
    serialNumber: "TSR3-2024-001",
    status: "available",
    condition: "excellent",
    purchaseDate: "2024-01-15",
    deposit: 500,
    dailyRate: 80,
  },
  {
    id: "e2",
    name: "Callaway 铁杆组",
    category: "club",
    brand: "Callaway",
    model: "Epic",
    serialNumber: "EPIC-2024-002",
    status: "borrowed",
    condition: "good",
    purchaseDate: "2024-02-20",
    deposit: 800,
    dailyRate: 120,
  },
  {
    id: "e3",
    name: "TaylorMade 球包",
    category: "bag",
    brand: "TaylorMade",
    status: "available",
    condition: "good",
    deposit: 200,
    dailyRate: 30,
  },
  {
    id: "e4",
    name: "高尔夫球车 #01",
    category: "cart",
    brand: "Club Car",
    status: "borrowed",
    condition: "fair",
    deposit: 1000,
    dailyRate: 200,
  },
  {
    id: "e5",
    name: "测距仪 Pro XE",
    category: "range_finder",
    brand: "Bushnell",
    status: "available",
    condition: "excellent",
    deposit: 300,
    dailyRate: 50,
  },
  {
    id: "e6",
    name: "FootJoy 球鞋(42码)",
    category: "shoes",
    brand: "FootJoy",
    status: "maintenance",
    condition: "fair",
    deposit: 150,
    dailyRate: 25,
  },
];

export const mockBorrowRecords: BorrowRecord[] = [
  {
    id: "b1",
    equipmentId: "e2",
    equipmentName: "Callaway 铁杆组",
    equipmentCategory: "club",
    borrowerId: "m1",
    borrowerName: "陈会员",
    borrowerPhone: "13800138001",
    applicantId: "u1",
    applicantName: "张前台",
    status: "active",
    borrowDate: "2024-05-28 09:00",
    expectedReturnDate: "2024-05-30 18:00",
    depositAmount: 800,
    depositPaid: true,
    bookingId: "booking1",
    memberId: "m1",
    memberName: "陈会员",
    createdAt: "2024-05-28 08:45",
    updatedAt: "2024-05-28 09:00",
    approvedBy: "u1",
    approvedByName: "张前台",
    approvedAt: "2024-05-28 08:50",
  },
  {
    id: "b2",
    equipmentId: "e4",
    equipmentName: "高尔夫球车 #01",
    equipmentCategory: "cart",
    borrowerId: "m2",
    borrowerName: "林先生",
    borrowerPhone: "13900139002",
    applicantId: "u1",
    applicantName: "张前台",
    status: "pending",
    borrowDate: "2024-05-30 10:00",
    expectedReturnDate: "2024-05-30 16:00",
    depositAmount: 1000,
    depositPaid: false,
    memberId: "m2",
    memberName: "林先生",
    createdAt: "2024-05-30 09:30",
    updatedAt: "2024-05-30 09:30",
  },
  {
    id: "b3",
    equipmentId: "e5",
    equipmentName: "测距仪 Pro XE",
    equipmentCategory: "range_finder",
    borrowerId: "m3",
    borrowerName: "王小姐",
    borrowerPhone: "13700137003",
    applicantId: "u2",
    applicantName: "李教练",
    status: "rejected",
    borrowDate: "2024-05-29 14:00",
    expectedReturnDate: "2024-05-29 18:00",
    depositAmount: 300,
    depositPaid: false,
    rejectedReason: "该时段已有其他预约",
    rejectedBy: "u3",
    rejectedByName: "王经理",
    rejectedAt: "2024-05-29 14:15",
    memberId: "m3",
    memberName: "王小姐",
    createdAt: "2024-05-29 13:50",
    updatedAt: "2024-05-29 14:15",
  },
  {
    id: "b4",
    equipmentId: "e3",
    equipmentName: "TaylorMade 球包",
    equipmentCategory: "bag",
    borrowerId: "m4",
    borrowerName: "赵先生",
    borrowerPhone: "13600136004",
    applicantId: "u1",
    applicantName: "张前台",
    status: "needs_review",
    borrowDate: "2024-05-27 08:00",
    expectedReturnDate: "2024-05-27 17:00",
    actualReturnDate: "2024-05-27 16:45",
    depositAmount: 200,
    depositPaid: true,
    memberId: "m4",
    memberName: "赵先生",
    createdAt: "2024-05-27 07:45",
    updatedAt: "2024-05-27 16:45",
    approvedBy: "u1",
    approvedByName: "张前台",
    approvedAt: "2024-05-27 07:50",
  },
  {
    id: "b5",
    equipmentId: "e1",
    equipmentName: "Titleist 一号木",
    equipmentCategory: "club",
    borrowerId: "m5",
    borrowerName: "孙女士",
    borrowerPhone: "13500135005",
    applicantId: "u1",
    applicantName: "张前台",
    status: "overdue",
    borrowDate: "2024-05-26 10:00",
    expectedReturnDate: "2024-05-28 18:00",
    depositAmount: 500,
    depositPaid: true,
    memberId: "m5",
    memberName: "孙女士",
    createdAt: "2024-05-26 09:45",
    updatedAt: "2024-05-26 10:00",
    approvedBy: "u1",
    approvedByName: "张前台",
    approvedAt: "2024-05-26 09:50",
  },
];

export const mockReturnInspections: ReturnInspection[] = [
  {
    id: "ri1",
    borrowRecordId: "b4",
    inspectorId: "u1",
    inspectorName: "张前台",
    inspectionDate: "2024-05-27 16:45",
    overallCondition: "fair",
    result: "damaged",
    issuesFound: ["球包底部有划痕", "肩带有磨损"],
    compensationAmount: 50,
    compensationReason: "底部划痕需要修复",
    notes: "归还时发现底部有明显划痕，已告知客户",
    depositReturned: true,
    depositReturnAmount: 150,
    createdAt: "2024-05-27 17:00",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking1",
    memberId: "m1",
    memberName: "陈会员",
    memberPhone: "13800138001",
    laneNumber: "A-03",
    date: "2024-05-28",
    startTime: "09:00",
    endTime: "12:00",
    status: "completed",
    guests: 2,
    bucketType: "large",
    bucketCount: 3,
    coachId: "u2",
    coachName: "李教练",
    totalAmount: 480,
    paidAmount: 480,
    createdAt: "2024-05-25 10:00",
  },
  {
    id: "booking2",
    memberId: "m2",
    memberName: "林先生",
    memberPhone: "13900139002",
    laneNumber: "B-01",
    date: "2024-05-30",
    startTime: "10:00",
    endTime: "14:00",
    status: "confirmed",
    guests: 4,
    bucketType: "medium",
    bucketCount: 4,
    totalAmount: 640,
    paidAmount: 640,
    createdAt: "2024-05-28 15:30",
  },
];

export const mockStoredValueRecords: StoredValueRecord[] = [
  {
    id: "sv1",
    memberId: "m1",
    memberName: "陈会员",
    type: "deposit",
    amount: 5000,
    balanceBefore: 0,
    balanceAfter: 5000,
    operatorId: "u1",
    operatorName: "张前台",
    notes: "首次充值",
    createdAt: "2024-05-01 10:00",
  },
  {
    id: "sv2",
    memberId: "m1",
    memberName: "陈会员",
    type: "consume",
    amount: 480,
    balanceBefore: 5000,
    balanceAfter: 4520,
    relatedType: "booking",
    relatedId: "booking1",
    relatedNote: "球道预约",
    operatorId: "u1",
    operatorName: "张前台",
    createdAt: "2024-05-28 09:00",
  },
  {
    id: "sv3",
    memberId: "m4",
    memberName: "赵先生",
    type: "consume",
    amount: 50,
    balanceBefore: 2000,
    balanceAfter: 1950,
    relatedType: "equipment",
    relatedId: "b4",
    relatedNote: "球包损坏赔偿",
    operatorId: "u3",
    operatorName: "王经理",
    createdAt: "2024-05-27 17:00",
  },
];

export const mockReviewCases: ReviewCase[] = [
  {
    id: "rc1",
    title: "赵先生球包损坏赔偿异议",
    type: "dispute",
    status: "investigating",
    priority: "medium",
    relatedBorrowIds: ["b4"],
    relatedMemberId: "m4",
    relatedMemberName: "赵先生",
    assigneeId: "u3",
    assigneeName: "王经理",
    description: "客户投诉球包底部划痕为原有损伤，不同意赔偿50元",
    timeline: [
      {
        id: "t1",
        timestamp: "2024-05-27 16:45",
        userId: "u1",
        userName: "张前台",
        action: "归还验收时发现划痕，记录赔偿",
      },
      {
        id: "t2",
        timestamp: "2024-05-27 17:30",
        userId: "m4",
        userName: "赵先生",
        action: "客户来电投诉，称划痕不是自己造成的",
      },
      {
        id: "t3",
        timestamp: "2024-05-28 09:00",
        userId: "u3",
        userName: "王经理",
        action: "已受理，正在调取借出前照片核实",
      },
    ],
    createdAt: "2024-05-27 17:30",
    updatedAt: "2024-05-28 09:00",
  },
  {
    id: "rc2",
    title: "孙女士一号木逾期未还",
    type: "damaged_equipment",
    status: "open",
    priority: "high",
    relatedBorrowIds: ["b5"],
    relatedMemberId: "m5",
    relatedMemberName: "孙女士",
    assigneeId: "u3",
    assigneeName: "王经理",
    description: "一号木预期归还日期已过2天，联系不上客户",
    timeline: [
      {
        id: "t1",
        timestamp: "2024-05-28 18:30",
        userId: "u1",
        userName: "张前台",
        action: "系统标记逾期",
      },
      {
        id: "t2",
        timestamp: "2024-05-29 10:00",
        userId: "u1",
        userName: "张前台",
        action: "电话无人接听，已发送短信提醒",
      },
      {
        id: "t3",
        timestamp: "2024-05-30 09:00",
        userId: "u3",
        userName: "王经理",
        action: "升级处理，准备启动赔偿流程",
      },
    ],
    createdAt: "2024-05-28 18:30",
    updatedAt: "2024-05-30 09:00",
  },
];

export const mockDashboardStats: DashboardStats = {
  pendingBorrows: 1,
  activeBorrows: 2,
  overdueBorrows: 1,
  rejectedToday: 1,
  pendingReturns: 0,
  needsReview: 1,
  openCases: 2,
};

export const getStatusBadgeStyle = (status: string) => {
  const styles: Record<string, string> = {
    pending: "bg-yellow-100 text-yellow-800",
    approved: "bg-blue-100 text-blue-800",
    rejected: "bg-red-100 text-red-800",
    active: "bg-green-100 text-green-800",
    returned: "bg-gray-100 text-gray-800",
    overdue: "bg-orange-100 text-orange-800",
    needs_review: "bg-purple-100 text-purple-800",
  };
  return styles[status] || "bg-gray-100 text-gray-800";
};

export const getStatusLabel = (status: string) => {
  const labels: Record<string, string> = {
    pending: "待审批",
    approved: "已批准",
    rejected: "已驳回",
    active: "借用中",
    returned: "已归还",
    overdue: "已逾期",
    needs_review: "待回查",
  };
  return labels[status] || status;
};

export const getRoleLabel = (role: string) => {
  const labels: Record<string, string> = {
    reception: "前台",
    coach: "教练",
    manager: "经理",
  };
  return labels[role] || role;
};

export const getCategoryLabel = (category: string) => {
  const labels: Record<string, string> = {
    club: "球杆",
    bag: "球包",
    cart: "球车",
    range_finder: "测距仪",
    shoes: "球鞋",
    umbrella: "雨伞",
    other: "其他",
  };
  return labels[category] || category;
};
