# Generated by Django 4.2.30 on 2026-05-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('water_quality', '水质问题'), ('facility', '设施问题'), ('coach', '教练问题'), ('service', '服务问题'), ('schedule', '排课问题'), ('other', '其他问题')], max_length=30, verbose_name='问题分类')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('assigned', '已分配'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭'), ('escalated', '已升级')], default='submitted', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('reporter_name', models.CharField(blank=True, max_length=50, verbose_name='报修人姓名')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='具体位置')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='现场照片')),
                ('expected_resolve_time', models.DateTimeField(blank=True, null=True, verbose_name='期望解决时间')),
                ('actual_resolve_time', models.DateTimeField(blank=True, null=True, verbose_name='实际解决时间')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('notes', models.TextField(blank=True, verbose_name='内部备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投诉/问题',
                'verbose_name_plural': '投诉/问题',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_internal', models.BooleanField(default=False, verbose_name='是否内部评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '处理记录',
                'verbose_name_plural': '处理记录',
                'ordering': ['created_at'],
            },
        ),
    ]
