# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='场馆名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='场馆编号')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='开门时间')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='关门时间')),
                ('status', models.CharField(choices=[('open', '营业中'), ('closed', '已关闭'), ('maintenance', '维护中')], default='open', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='面积(㎡)')),
                ('seat_count', models.IntegerField(default=0, verbose_name='座位数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_venues', to=settings.AUTH_USER_MODEL, verbose_name='场馆经理')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
                'db_table': 'venues',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VenueArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, verbose_name='区域编号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='venues.venue', verbose_name='所属场馆')),
            ],
            options={
                'verbose_name': '场馆区域',
                'verbose_name_plural': '场馆区域',
                'db_table': 'venue_areas',
                'unique_together': {('venue', 'code')},
            },
        ),
    ]
