# Generated by Django 4.2.7 on 2026-05-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('registering', '报名中'), ('upcoming', '即将开始'), ('in_progress', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('registration_start', models.DateTimeField(verbose_name='报名开始时间')),
                ('registration_end', models.DateTimeField(verbose_name='报名结束时间')),
                ('max_participants', models.IntegerField(default=50, verbose_name='最大参与人数')),
                ('min_participants', models.IntegerField(default=0, verbose_name='最少参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前报名人数')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_need_checkin', models.BooleanField(default=True, verbose_name='需要签到')),
                ('checkin_code', models.CharField(blank=True, max_length=20, verbose_name='签到码')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='封面图片')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activities',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编号')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '活动分类',
                'verbose_name_plural': '活动分类',
                'db_table': 'activity_categories',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('checked_in', '已签到'), ('no_show', '未到场')], default='pending', max_length=20, verbose_name='状态')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('checkin_method', models.CharField(blank=True, max_length=50, verbose_name='签到方式')),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='志愿服务时长')),
                ('feedback_rating', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('feedback_comments', models.TextField(blank=True, verbose_name='反馈意见')),
                ('feedback_time', models.DateTimeField(blank=True, null=True, verbose_name='反馈时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comments', models.TextField(blank=True, verbose_name='审核意见')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'db_table': 'activity_registrations',
                'ordering': ['-registration_time'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_description', models.TextField(verbose_name='任务描述')),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='实际服务时长')),
                ('issues_encountered', models.TextField(blank=True, verbose_name='遇到的问题')),
                ('suggestions', models.TextField(blank=True, verbose_name='建议')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='问题已解决')),
                ('handle_notes', models.TextField(blank=True, verbose_name='处理备注')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_feedbacks', to='activities.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '志愿者反馈',
                'verbose_name_plural': '志愿者反馈',
                'db_table': 'volunteer_feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
