// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/31/2026, 7:54:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/zhangliu/Documents/private/model-test/trae-test-5/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/plugins/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/stores/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/types/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/utils/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/composables/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-test-5/client/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;